orgzly/orgzly-android

app/src/androidTest/java/com/orgzly/android/espresso/EspressoUtils.java, app/src/main/java/com/orgzly/android/Shelf.java, app/src/main/java/com/orgzly/android/prefs/AppPreferences.java, app/src/main/res/values/preferences_keys.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
Fixes #17. Depends on orgzly/org-java#2.
=> Add option to disable separation of header and content with an empty line

app/src/androidTest/java/com/orgzly/android/espresso/EspressoUtils.java, app/src/androidTest/java/com/orgzly/android/espresso/SyncingTest.java, app/src/main/java/com/orgzly/android/prefs/AppPreferences.java, app/src/main/java/com/orgzly/android/ui/fragments/SyncFragment.java, app/src/main/res/values/preferences_keys.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
Hi,
I added the the option to sync after a new note is created. 
It works but sometimes it has a problem. As I really want to start understanding the project I would really appreciate if someone would take a look and tell me what is wrong. Sometimes after new note creation, `BooksClient.isModifiedAfterLastSync()` is still true therefore the out-of-date indicator besides notebook is visible. It only happens on my emulator while it works fine on my actual phone.
=> Sync after new note is created

app/src/androidTest/java/com/orgzly/android/espresso/EspressoUtils.java, app/src/main/java/com/orgzly/android/Notifications.java, app/src/main/java/com/orgzly/android/prefs/AppPreferences.java, app/src/main/java/com/orgzly/android/sync/SyncService.java, app/src/main/res/values/preferences_keys.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
Fixes #89.
This PR adds a sync action to the ongoing notification and adds two new notifications, related to sync:
- the first is displayed while the sync is running
- the second is displayed, if an error occurred during sync or there are conflicts
The notifications have to be enabled in the settings.
=> Add sync action to new note notification and add sync notifications

app/src/androidTest/java/com/orgzly/android/espresso/ShareActivityTest.java, app/src/androidTest/java/com/orgzly/android/util/QueryUtilsTest.java, app/src/main/java/com/orgzly/android/AppIntent.java, app/src/main/java/com/orgzly/android/Notifications.java, app/src/main/java/com/orgzly/android/ui/ShareActivity.java, app/src/main/java/com/orgzly/android/util/QueryUtils.java, app/src/main/java/com/orgzly/android/widgets/ListWidgetProvider.java
This change implements a convenience feature by selecting the book from the filter defined in current widget view. As filter can get very complex, I've tried to narrow it down to first positive occurrence of a book. While this implementation is far from perfect IMHO this reduces a minor inconvenience and saves a couple of seconds a day.
=> Preset book on new note view from filter query

app/src/main/java/com/orgzly/android/provider/Database.java, app/src/main/java/com/orgzly/android/provider/Provider.java, app/src/main/java/com/orgzly/android/provider/clients/NotesClient.java, app/src/main/java/com/orgzly/android/provider/models/DbNote.java, app/src/main/java/com/orgzly/android/provider/models/DbNoteContentTime.java, app/src/main/java/com/orgzly/android/provider/models/DbNoteContentTimeColumns.java, app/src/main/java/com/orgzly/android/ui/HeadsListViewAdapter.java, app/src/main/java/com/orgzly/android/ui/fragments/NoteFragment.java
This is a work in progress for fixing #76.
I've added a new relationship `note_content_times` and modified `Provider.loadBookFromReader` to populate the table.
I guess the next step is to update this table whenever the content changes, and to cleanup when the note is destroyed.
Then, we should be able to lookup in this table for agenda searches and reminders.
Am I on the right track?  Don't be afraid to tell me if not. :)
=> Support plain timestamps

README.org
The link was shortened and was redirecting to a non-existent page.
=> Correct link on how to disable animations.

app/src/main/java/com/orgzly/android/ui/HeadsListViewAdapter.java, app/src/main/java/com/orgzly/android/ui/fragments/NoteFragment.java, app/src/main/java/com/orgzly/android/ui/views/TextViewWithMarkup.kt, app/src/main/java/com/orgzly/android/ui/views/style/CheckboxSpan.kt, app/src/main/java/com/orgzly/android/util/OrgFormatter.kt, app/src/main/res/layout/fragment_note.xml, app/src/main/res/raw/orgzly_getting_started.org
Issue #58 
This is a suggested implementation of checkboxes, which probably needs some polishing before merging. I'm creating the pull request to get some feedback/advice for (possibly) improving the implementation.
The checkboxes work as follows:
- When you edit the content of a note, "c " at the beginning of a line is automatically replaced by "[ ] ". This is to make it easier to write checkboxes (easier than writing brackets).
- When you view a note, the checkboxes are shown in monospace font, green if "[X]" and red if "[ ]".
- Checkboxes can be checked/unchecked by clicking them.
- It seems that some other formatting (bold etc.) is lost as it is now. I need to fix this.
Possible improvements:
- Using the same exact color for checkboxes as for TODO/DONE
- Using a proper Android …
=> Add possibility to check/uncheck checkboxes

app/src/main/AndroidManifest.xml, app/src/main/java/com/orgzly/android/BookUtils.java, app/src/main/java/com/orgzly/android/NewNoteBroadcastReceiver.java, app/src/main/java/com/orgzly/android/Notifications.java, app/src/main/java/com/orgzly/android/provider/clients/NotesClient.java, app/src/main/java/com/orgzly/android/ui/ShareActivity.java, app/src/main/res/values/strings.xml
When entering notes I want to be able to quickly write something and store it away to deal with later. At the moment this involves me opening a screen with lots of fields, filling in the one field I care about (the title), then saving the note. I would much rather use the "quick reply" feature on the notification to be able to enter a note, without interrupting what I am currently doing. This is similar to the way I use `org-capture`.
This PR contains code to implement this. I'm not _completely_ happy with it, but I like to start a conversation with a proof of concept. I'm not familiar with how Orgzly works, so it's likely that I have not done this the right way.
=> Add "quick reply" to notification as a way to add new notes

app/src/main/AndroidManifest.xml, app/src/main/java/com/orgzly/android/App.java, app/src/main/java/com/orgzly/android/ui/CommonActivity.kt, app/src/main/java/com/orgzly/android/ui/CommonActivityLifecycleCallbacks.java, app/src/main/java/com/orgzly/android/util/AppPermissions.kt, app/src/main/java/com/orgzly/android/util/OrgFormatter.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/file_paths.xml
Hello,
This is an attempt at implementing file links within orgzly (linked to #360).
Fow now, it will only work with the `file:path` link form, but tuning the regex might enable other forms.
This MR uses the file provider of Android, which should apparently be the way to go since Android 7.0. It tries to find the file links in the content, creates a `content://` link for a file in the internal storage (Right now the base path is /sdcard) and finally tries to open the file with an `ACTION_VIEW` intent.
This seems to be working quite fine, as I tested it and was able to open png, jpg and pdf files (on the Pixel 2 XL emulator with Android 8.1).
Things that won't be working as of now:
- If you have a space in the path to your file, the regex matcher will stop at it, preventing you to get the …
=> Handle "file:" links for opening files on android storage

app/src/main/java/com/orgzly/android/ui/CommonActivity.kt
Hello,
This MR should fix #348.
The behavior before this MR when changing a setting and going back to notebook list was: onResume, onResumeFragments, onPause, onResume, onResumeFragments and onPause, thus blocking the UI by removing actions from the `LocalBroadcastManager` with the last onPause.
This MR changes the behavior of CommonActivity, so the call stack becomes: onResume, onResumeFragments, onPause, onResume and onResumeFragments, leaving all the actions available to the `LocalBroadcastManager`.
=> Fix broken UI actions after setting change

app/build.gradle, app/src/main/java/com/orgzly/android/prefs/AppPreferences.java, app/src/main/java/com/orgzly/android/ui/ImageLoader.kt, app/src/main/res/values/prefs_keys.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_screen_notebooks.xml
Hello,
Following the work on #382, I open a PR with new propositions.
I reworked the code a bit to better integrate it with the previous code, and notably to handle `[[...]]` for file links (still linked to #360) in addition to the previous `file:` scheme.
I also added an ImageSpan to display images in notes (rescaled to fit width, if larger than the window width), as a proposition to implement #147.
As before, this PR has been tested with API 16 (Nexus 5), API 23 (Pixel 2) & API 27 (Pixel 2 XL)
A small note sample, I used to test this:
```
[[Download/test.jpg]]
file:Download/test2.png
[[Download/test3.png][Test]]
```
Right now, named links are not replaced with an ImageSpan.
Furthemore regarding to the application performance, maybe adding a setting to toggle off image display could be a …
=> Allow "file:" and "[[...]]" links, display images in notes

app/src/main/AndroidManifest.xml, app/src/main/java/com/orgzly/android/Book.java, app/src/main/java/com/orgzly/android/ChooserShareTargetService.kt, app/src/main/res/values/strings.xml
Do we want to allow sharing directly to individual notebooks from Android M, using the "direct share" feature?
Perhaps we also need a way to let the user control which books should be share targets?
=> Allow Android M Direct Share to individual Orgzly books

app/src/main/AndroidManifest.xml, app/src/main/java/com/orgzly/android/di/module/AndroidModule.kt, app/src/main/java/com/orgzly/android/ui/BookChooserActivity.java, app/src/main/java/com/orgzly/android/ui/CaptureChooserActivity.java, app/src/main/java/com/orgzly/android/ui/TemplateChooserActivity.java, app/src/main/java/com/orgzly/android/ui/share/ShareActivity.java, app/src/main/res/values/strings.xml
Related issue: https://github.com/orgzly/orgzly-android/issues/80 
This is a very minimalistic implementation, basically, just a shorthand to creating a note in a specific notebook. But it'd be a necessary step towards implementing proper capture anyway, so I think it makes sense to do it now considering that actually supporting templates would be a bit more complicated.
In my vision, in future when we do support templates, you'd just have a UI prompting you for notebook and also asking you to choose from one of the predefined capture templates. Then the template is passed to the share intent and handled by the fragment that creates notes (e.g. filling up default todo state/tags/etc). If you don't recieve a template in the intent, you just create a note in the target notebook. So the …
=> Basic org-capture implementation

app/src/main/java/com/orgzly/android/widgets/ListWidgetService.kt
More convenience.
There is no reason to block the ability to mark notes "done" from the widget.
=> Widget: show check mark for NOTEs as well

app/src/main/AndroidManifest.xml, app/src/main/java/com/orgzly/android/ui/share/ShareActivity.java
Thanks for this app and for making it open source. I love orgzly. To quickly annotate/schedule photos or screenshots I needed orgzly to allow me to share image files with it. So I added the code for this functionality. 
I built and tested it with success on my device. 
Thanks again.
P.S.: Line 6, 10 and 11 in AndroidManifest.xml are not needed leftovers inserted while getting the app to run on my device beside the 'real' orgzly app. Sorry for leaving them in the commit. They can be removed. Let me now if I shall add a new commit to remove them. I ended up using applicationIdSuffix ".debug" inside the debug buildType in the build.gradle file instead.
=> Enable orgzly to receive shared image

app/src/main/java/com/orgzly/android/prefs/AppPreferences.java, app/src/main/java/com/orgzly/android/prefs/TimePreference.kt, app/src/main/java/com/orgzly/android/prefs/TimePreferenceFragment.kt, app/src/main/java/com/orgzly/android/reminders/ReminderService.kt, app/src/main/java/com/orgzly/android/ui/settings/SettingsFragment.kt, app/src/main/res/layout/pref_dialog_time.xml, app/src/main/res/values/prefs_keys.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml-v26/prefs_screen_reminders.xml, app/src/main/res/xml/prefs_screen_reminders.xml
This fixes #651.
The default time for this preference is still 9 o'clock, like it was before. But now a user is able to change this time.
=> Add preference to set default reminder time

app/src/androidTest/java/com/orgzly/android/OrgzlyTest.java
The Android OS permissions dialog pops up the first time you run this test
According to the javadoc of `GrantPermissionRule`, "Once a permission is granted it will apply for all tests running in the current Instrumentation" so I added it to to the top-level test to avoid ambiguity when the test runner chooses a different test ordering
=> Grant storage permission in tests to prevent BooksTest.testExport failing

app/src/main/java/com/orgzly/android/ui/views/EditTextWithMarkup.kt, app/src/main/java/com/orgzly/android/util/OrgFormatter.kt
**Description**: 
Make Orgzly recognize `+` as a valid bullet symbol for unordered lists  
**Implemented**:
**References**: 
* [Org-Mode: Plain Lists](https://www.gnu.org/software/emacs/manual/html_node/org/Plain-lists.html)
* 8e0493725b116d34004ba8dbd454bd49cdd5d033: Recognizing `-` as valid bullet for plain list item
Resolves #558
=> Recognize + as valid bullet symbol for unordered lists

.github/workflows/android-build-master.yml
This change leverages Github Actions workflow to:
1. Verify Orgzly builds successfully for any submitted Pull Requests
2. Simplify testing submitted changes by generating debug apk 
3. Ensure master builds after a PR is merged (or on direct commits to master)   
Screenshot from [Workflow](https://github.com/debanjum/orgzly-android/actions/runs/116095491)
=> Build Orgzly on PR create or merge via Github Actions

app/src/main/java/com/orgzly/android/LocalStorage.java
Currently the external cache directory with a fallback to the internal one is used by Orgzly to store temporary book files when syncing. This directory resides on the primary shared/external storage which is accessible by all applications having READ_EXTERNAL_STORAGE permission. For extra context I am quoting the [documentation of Context.getExternalCacheDir()](https://developer.android.com/reference/android/content/Context.html#getExternalCacheDir()):
> There is no security enforced with these files. For example, any application holding Manifest.permission.WRITE_EXTERNAL_STORAGE can write to these files.
I am fairly certain that there are shady apps or just shady SDKs used by reputable apps that constantly monitor the shared storage for changes and analyze/filter/upload interesting data. …
=> Use only the internal cache directory for temporary book files

app/src/main/java/com/orgzly/android/git/GitFileSynchronizer.java, app/src/main/java/com/orgzly/android/repos/GitRepo.java, app/src/main/java/com/orgzly/android/repos/TwoWaySyncRepo.kt, app/src/main/java/com/orgzly/android/sync/SyncService.kt
The rationale behind this is that I have found Git syncing multiple notebooks over SSH to be very slow. I realized that separate SSH sessions were being initiated for each updated notebook.
I believe there is no reason to initiate more than two SSH sessions: one for fetch the repo, and one for pushing it after all commits have been made.
=> Git push over SSH only once per sync

app/src/main/java/com/orgzly/android/prefs/AppPreferences.java, app/src/main/java/com/orgzly/android/ui/ImageLoader.kt, app/src/main/java/com/orgzly/android/usecase/LinkFindTarget.kt, app/src/main/res/values/prefs_keys.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_screen_notebooks.xml
Addresses #496 
Current behavior was
- `file:/xxx` relative to root.
- `file:xxx` relative to Environment.getExternalStorageDirectory().getPath().
The new behavior in this commit is:
- `file:/xxx` relative to pref AppPreferences#fileAbsoluteRoot(), default to "/" 
- `file:xxx` relative to pref AppPreferences#fileRelativeRoot(), default to Environment.getExternalStorageDirectory().getPath()
Added two basic settings in the Image category for these two prefs. The setting is text only, could potentially be directoyr picker.
The path following behavior is changed in `ImageLoader` and `Widget.followLinkToFile`, now both uses `LinkFindTarget`.
=> Add two settings to configure relative path for file links.

app/src/main/java/com/orgzly/android/git/GitFileSynchronizer.java, app/src/main/java/com/orgzly/android/repos/GitRepo.java, app/src/main/java/com/orgzly/android/repos/TwoWaySyncResult.kt, app/src/main/java/com/orgzly/android/sync/SyncService.kt, app/src/main/res/values/strings.xml
Relates to #24.
These changes mean that a sync conflict (merge conflict) no longer prevents any syncing from taking place.
Now, the user can keep syncing to the temporary branch until the merge conflict has been resolved.
Each time syncing takes place, Orgzly will make an attempt to return to the main ranch.
The user can resolve the conflict on the temporary branch, or by merging back to the main branch; it should not matter.
A warning is displayed each time a sync results in Orgzly staying on a temporary branch. This is to remind the user that a merge conflict needs to be resolved outside of Orgzly.
=> Git: Useful merge branches

app/src/main/java/com/orgzly/android/ui/CommonActivity.kt, app/src/main/res/values-night/styles.xml, app/src/main/res/values-ru-rRU/strings.xml, app/src/main/res/values/prefs_keys.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
Resolves #797
I took the lazy approach and created new theme that references existing `AppLightTheme` and `AppDarkTheme` themes for day and night modes repectively.
Better solution wold be to implement new theme based on `Theme.AppCompat.DayNight.NoActionBar` and remove `AppLightTheme` & `AppDarkTheme`. I can do that but decided to ask if it is ok with project roadmap first.
Also, I managet to add string resources for English and Russian only.
=> Add light/dark theme that follows system setting

app/build.gradle, app/src/main/java/com/orgzly/android/data/DataRepository.kt, app/src/main/java/com/orgzly/android/ui/main/MainActivity.java, app/src/main/java/com/orgzly/android/ui/main/SharedMainActivityViewModel.kt, app/src/main/java/com/orgzly/android/ui/notes/NotesFragment.kt, app/src/main/java/com/orgzly/android/ui/notes/book/BookFragment.kt, app/src/main/java/com/orgzly/android/ui/notes/query/QueryFragment.kt, app/src/main/java/com/orgzly/android/ui/notes/quickbar/QuickBar.kt, app/src/main/java/com/orgzly/android/usecase/NoteUpdateClockingState.kt, app/src/main/java/com/orgzly/android/util/OrgFormatter.kt, app/src/main/res/drawable/ic_hourglass_bottom.xml, app/src/main/res/drawable/ic_hourglass_disabled.xml, app/src/main/res/drawable/ic_hourglass_top.xml, app/src/main/res/values/attrs.xml, app/src/main/res/values/quick_bar_ids.xml, app/src/main/res/values/styles.xml
Hello,
This PR should fix #15. The basic functionalities should be covered.
What is implemented:
What remains to be fixed:
- Maybe having a clock icon with an arrow going in for clock-in, a clock icon with with an arrow going out for clock-out and a button with the strikethrough clock for org-cancel ?
=> using the hourglass_{top, bottom, disabled} material icons
- [ ] The regexes in OrgFormatter might be moved to OrgPatterns
Thanks for your comments and suggestions for improvements !
=> Add Clocking / Time capture implementation
